version: 2

jobs:
  py367:
    working_directory: ~/automatminer
    docker:
      - image: circleci/python:3.6.7
        environment:
          CODACY_PROJECT_TOKEN: "0cdf090f6d5f4f8783fcf3ce04c6a1d6"
          CI: "CIRCLE"
    steps:
      - checkout

    # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: setup env and run tests
          command: |
            python3 -m venv test_env
            . test_env/bin/activate
            pip install -q --upgrade pip
            pip install --quiet -r requirements.txt

            # pip install --quiet -r requirements-optional.txt

            pip install -e .
            pip install -q coverage
            pip install -q codacy-coverage

            coverage run setup.py test
            coverage xml
            python-codacy-coverage -r coverage.xml
          no_output_timeout: 120m

      - save_cache:
          paths:
          - ./test_env
          key: v1-dependencies-{{ checksum "requirements.txt" }}


  py372:
    working_directory: ~/matminer
    docker:
      - image: circleci/python:3.7.2
        environment:
          CI: "CIRCLE"
    steps:
      - checkout

    # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: setup env and run tests
          command: |
            python3 -m venv test_env
            . test_env/bin/activate
            pip install -q --upgrade pip
            pip install --quiet -r requirements.txt

            # pip install --quiet -r requirements-optional.txt

            pip install -e .
            pip install -q coverage
            pip install -q codacy-coverage

            coverage run setup.py test
            coverage xml
            python-codacy-coverage -r coverage.xml
          no_output_timeout: 120m

      - save_cache:
          paths:
          - ./test_env
          key: v1-dependencies-{{ checksum "requirements.txt" }}


workflows:
  version: 2
  build_and_test:
    jobs:
      - py367
      - py372